### ISSUE TITLE
Import error while using in conda env

### ISSUE THREAD

**Issue by steph-ben** [metwork-framework/directory_observer#4]
Hi there,

Glad to see this module as an standalone python package !

I tried to install it in a fresh conda env, but using it failed with an mflog import error
Any idea ? I guess inside mfdata it works fine.

Best regards,
Stéphane

----

* Issue description
```
$ directory_observer 
Traceback (most recent call last):
  File "/home/steph/miniconda3/envs/met/bin/directory_observer", line 5, in <module>
    from directory_observer.directory_observer import main
  File "/home/steph/miniconda3/envs/met/lib/python3.10/site-packages/directory_observer/directory_observer.py", line 16, in <module>
    from mflog import getLogger
ModuleNotFoundError: No module named 'mflog'
```

* Reproduction steps
```
# Install python with conda
$ conda create -n met
$ conda activate met
$ conda install -y python
$ python -V
Python 3.10.4

# Package installation with pip work great !
$ pip install git+https://github.com/metwork-framework/directory_observer.git
...
Successfully built directory-observer pyinotify
Installing collected packages: pyinotify, wrapt, pyparsing, MarkupSafe, async-timeout, packaging, jinja2, deprecated, redis, opinionated_configparser, directory-observer
Successfully installed MarkupSafe-2.1.1 async-timeout-4.0.2 deprecated-1.2.13 directory-observer-0.0.1 jinja2-3.1.1 opinionated_configparser-1.0.1 packaging-21.3 pyinotify-0.9.6 pyparsing-3.0.8 redis-4.2.2 wrapt-1.14.0
```
* Versions

```
$ pip freeze
async-timeout==4.0.2
Deprecated==1.2.13
directory-observer @ git+https://github.com/metwork-framework/directory_observer.git@5090ee997b786bb4ab9a48a0ceb12317f138d8e8
Jinja2==3.1.1
MarkupSafe==2.1.1
opinionated-configparser==1.0.1
packaging==21.3
pyinotify==0.9.6
pyparsing==3.0.8
redis==4.2.2
wrapt==1.14.0
```

**Comment by thebaptiste** [comment]
I think the reason is probably that mflog is missing as a dependency of directory_observer.

**Comment by thebaptiste** [comment]
I have added mflog as dependency.
Please @steph-ben let me know if it has fixed your problem.

But I am not sure that directory_observer is designed to work properly outside Metwork environment...
